<?php echo $this->render('header.phtml'); ?>
<h1><?php echo $this->escape($this->title); ?></h1>
<form action="<?php echo $this->baseUrl; ?>/index/add" method="post" >
    <label for="artist">Artist:</label>
    <input type="text" name="artist" class="form-control"/>
    <br/>
    <label for="title">Title:</label>
    <input type="text" name="title" class="form-control"/>
    <br/>
    <button type="submit" class="btn btn-primary">Add Album </button>
</form>
<?php echo $this->render('footer.phtml'); ?>
