<h1>Editar Álbum</h1>
<form method="post">
    <label for="artist">Artista:</label>
    <input type="text" name="artist" value="<?php echo $this->escape($this->album->artist); ?>" required>
    <br>
    <label for="title">Título:</label>
    <input type="text" name="title" value="<?php echo $this->escape($this->album->title); ?>" required>
    <br>
    <input type="submit" value="Actualizar">
</form>
