<?php echo $this->render('header.phtml'); ?>
<h1>Editar Álbum</h1>
<form method="post">
    <label for="artist">Artista:</label>
    <input type="text" name="artist" value="<?php echo $this->escape($this->album->artist);?>" class="form-control" required>
    <br>
    <label for="title">Título:</label>
    <input type="text" name="title" value="<?php echo $this->escape($this->album->title);?>" class="form-control" required>
    <br>
    <button type="submit" class="btn btn-success">Actualizar</button>
</form>
<?php echo $this->render('footer.phtml'); ?>
